---
title: "My portfolio"
output:
  html_document:
    code_folding: hide
    theme: spacelab
  pdf_document: default
  word_document: default
---

```{r backend, message=FALSE, warning=FALSE}
require(ggplot2)
require(ggthemes)
require('dplyr')
require(reshape2)
library(knitr)
require(scales)
#theme_set(theme_gray())

data = read.csv("/Users/chg/Documents/budget.csv")
data$Date <- as.Date(data$Date, "%d.%m.%Y")

data$Cash.Euro.ZL <- data$Cash.Euro * data$EURPLN
data$Cash.USD.ZL <- data$Cash.USD * data$USDPLN
data$Cash.DK.ZL <- sapply(data$Cash.DK, function(x) 0.57764*x)
data$Sum <- rowSums(data[c("Cash", "Cash.Company", "Deposit", "Mutual.Funds", "Stock.Market", "Cash.USD.ZL", "Cash.Euro.ZL", "Cash.DK.ZL")])
data$SumInvested <- rowSums(data[c("Cash", "Cash.Company", "Deposit", "Mutual.Funds.Invested", "Stock.Market.Invested", "Cash.USD.ZL", "Cash.Euro.ZL", "Cash.DK.ZL")])
d <- subset(data, select=c("Date",  "Cash","Cash.Company", "Deposit", "Mutual.Funds","Stock.Market", "SumInvested", "Cash.Euro.ZL", "Cash.USD.ZL", "Stock.Market.Invested", "Mutual.Funds.Invested", "Cash.DK.ZL", "Sum"))
mdata <- melt(d, id='Date')

drawPlot <- function(mdata) {
  options(scipen=10000)
  ggplot(data=mdata, aes(x=Date, y=value, colour=variable)) + geom_line() +
    labs(x="Date", y="zl", title="Net worth") +
    theme(legend.title=element_blank()) +
    guides(colour = guide_legend(override.aes = list(size=8))) +
    #stat_smooth(data = melt(subset(data, select=c("Sum", "Date")), id="Date"), method = 'lm', aes(colour = 'Trend'), se = FALSE) +
    scale_y_continuous(expand = c(0, 0))
}

consecutiveDiff <- function(s) {
  w <- vector()
  for (i in 1:length(s)-1) {
    w[i] <- s[i+1] - s[i]
  }
  return(w)
}
w <- consecutiveDiff(tail(data$Sum, n=13))
```

Asset allocation overview.

```{r fig.width=13, fig.height=10}
drawPlot(mdata)
```

Last '12 months' monthly diff:
```{r}
kable(t(w), col.names=tail(format(data$Date,"%B"), n=12), digits=2)
```

**The mean diff for last 12 months**
```{r}
print(mean(w))
```

**Last 6 month totals:**
```{r}
kable(t(tail(data$Sum, n=6)), col.names=tail(format(data$Date,"%B"), n=6), digits=2)
```

**Portfolio allocation**
```{r}
last = function(x) { tail(x, n=1) }
sum = last(data$Sum)
foreignCashRatio = (last(data$Cash.USD.ZL) + last(data$Cash.Euro.ZL) + last(data$Cash.DK.ZL)) / sum
stocksRatio = last(data$Stock.Market) / sum
fundsRatio = last(data$Mutual.Funds) / sum
cash = (last(data$Cash) + last(data$Cash.Company) + last(data$Deposit)) / sum
ratios = c(cash, foreignCashRatio, stocksRatio, fundsRatio)
colu = c("Cash", "Currencies", "Stocks", "Funds")
b <- data.frame(ratio=ratios, what=colu)
bar <- ggplot(b, aes(x=1, y=b$ratio, fill=b$what)) + geom_bar(width = 1, stat = "identity", color='black') +
       coord_polar(theta='y') +
       theme(axis.ticks=element_blank(),  # the axis ticks
                   axis.title=element_blank(),  # the axis labels
                   axis.text.y=element_blank()) + # the 0.75, 1.00, 1.25 labels.
       theme(axis.text.x=element_text(color='black'), legend.title=element_blank())
bar
```
```{r}
kable(t(percent(ratios)), col.names = colu)
```

